spring:
  datasource:
    url: jdbc:mysql://localhost:3306/**
    password: ***
    username: ***
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ALWAYS
      schema-locations:
          classpath:data\schema.sql

      data-locations:
        - classpath:data\data.sql
server:
  port: 8081

mybatis:
  config-location: classpath:mybatis-config.xml